### ISSUE TITLE
Dimension of graph kernels

### ISSUE THREAD

**Issue by williamweiwu** [se-ok/WLsimilarity#3]
Hi,

In the experiment of graph classification with graph kernels, how can I set the number of the reduced dimensions of each node? My understanding of graph classification with graph kernels is that in each graph, each node is embedded into 200-dimensional space, and then the algorithms get kernels.

I can find '200' in configs/TUs_graph_classification_kernels.json, but it is just in WLS and WLSLin. However, I cannot find the dimension setting in other algorithms.

Thanks
Wei

**Comment by se-ok** [comment]
Hi Wei,

The point of graph kernels is that we do not learn parameters via sort-of training, although there are hyperparameters which are preset.
The 'dimension' for WLS and WLSLin came from the use of 'feature maps',
while for the other aggregation methods we do not need to specify the dimension.
The dimension for each node in the latter shall stay the same as the input node feature dimension, which is given by the data.

If something is still unclear, please point to a specific point so that I can elaborate further.

Best,
Seongmin

**Comment by williamweiwu** [comment]
> Hi Wei,
> 
> The point of graph kernels is that we do not learn parameters via sort-of training, although there are hyperparameters which are preset.
> The 'dimension' for WLS and WLSLin came from the use of 'feature maps',
> while for the other aggregation methods we do not need to specify the dimension.
> The dimension for each node in the latter shall stay the same as the input node feature dimension, which is given by the data.
> 
> If something is still unclear, please point to a specific point so that I can elaborate further.
> 
> Best,
> Seongmin

Hi Seongmin,

Thank you for your quick reply.

Considering your patient explanation, my understanding for the graph kernel experiment is as follows:
1. Each graph is embedded to compute the kernel between any two graphs, as shown in the code "main_TUs_kernels.py"
2. It doesn't require massive parameter learning, which is common in GNNs.
3. Only WLS and WLSLin map each node into a low-dimensional feature space.

Are they right? I would appreciate your help very much!

Thanks
Wei

**Comment by se-ok** [comment]
Hi Wei,

It appears to me that there is a slight misunderstanding.
Your description is mostly correct except that WLS is not mapping into low-dimensional space, but actually increase the dimension in most cases. I shall write a bit lengthy explanation below.

Let me say that we run graph kernel experiment using BZR dataset.
According to [TU datasets](https://ls11-www.cs.tu-dortmund.de/staff/morris/graphkerneldatasets), each node in a graph from BZR dataset has a 3-dimensional vector(feature) assigned.

First I explain the overall flow.
What WLS-like graph kernel does is to iteratively update each node's representation using its neighbors' representations.
After fixed number of iterations, for each graph, the node representations are gathered (sum / mean) to represent the graph.
Now we obtained graph representation, and it is used to compute the graph similarity, via well-known kernels such as linear / rbf.
Graph classification is done via Support Vector Classifier, provided by scikit-learn package.

Now about your question.
For other aggregation methods, such as GraphSage, GAT, GCN, WWL,
each node aggregates the neighboring nodes' attributes depending on the model, "without transforming."
Thus the node feature dimension never change throughout the model. Therefore, the node feature dimension for GraphSage, GAT, GCN, WWL, and actually WLSLin will stay at 3 for BZR experiment.
However, for WLS, I adopted so-called "feature map" which does change the dimension, but without parameter learning.
And in most cases it increases the dimension, so it is different from "mapping into low-dimensional feature space".

I noticed that WLSLin configuration contains "hidden_dim" and "out_dim" parameters but because of "kernel_name" being "linear", the dimensions should not affect the calculation for WLSLin.

Hope it helps,
Seongmin

**Comment by williamweiwu** [comment]
> > Hi Wei,
> > The point of graph kernels is that we do not learn parameters via sort-of training, although there are hyperparameters which are preset.
> > The 'dimension' for WLS and WLSLin came from the use of 'feature maps',
> > while for the other aggregation methods we do not need to specify the dimension.
> > The dimension for each node in the latter shall stay the same as the input node feature dimension, which is given by the data.
> > If something is still unclear, please point to a specific point so that I can elaborate further.
> > Best,
> > Seongmin
> 
> Hi Seongmin,
> 
> Thank you for your quick reply.
> 
> Considering your patient explanation, my understanding for the graph kernel experiment is as follows:
> 
> 1. Each graph is embedded to compute the kernel between any two graphs, as shown in the code "main_TUs_kernels.py"
> 2. It doesn't require massive parameter learning, which is common in GNNs.
> 3. Only WLS and WLSLin map each node into a low-dimensional feature space.
> 
> Are they right? I would appreciate your help very much!
> 
> Thanks
> Wei




> Hi Wei,
> 
> It appears to me that there is a slight misunderstanding.
> Your description is mostly correct except that WLS is not mapping into low-dimensional space, but actually increase the dimension in most cases. I shall write a bit lengthy explanation below.
> 
> Let me say that we run graph kernel experiment using BZR dataset.
> According to [TU datasets](https://ls11-www.cs.tu-dortmund.de/staff/morris/graphkerneldatasets), each node in a graph from BZR dataset has a 3-dimensional vector(feature) assigned.
> 
> First I explain the overall flow.
> What WLS-like graph kernel does is to iteratively update each node's representation using its neighbors' representations.
> After fixed number of iterations, for each graph, the node representations are gathered (sum / mean) to represent the graph.
> Now we obtained graph representation, and it is used to compute the graph similarity, via well-known kernels such as linear / rbf.
> Graph classification is done via Support Vector Classifier, provided by scikit-learn package.
> 
> Now about your question.
> For other aggregation methods, such as GraphSage, GAT, GCN, WWL,
> each node aggregates the neighboring nodes' attributes depending on the model, "without transforming."
> Thus the node feature dimension never change throughout the model. Therefore, the node feature dimension for GraphSage, GAT, GCN, WWL, and actually WLSLin will stay at 3 for BZR experiment.
> However, for WLS, I adopted so-called "feature map" which does change the dimension, but without parameter learning.
> And in most cases it increases the dimension, so it is different from "mapping into low-dimensional feature space".
> 
> I noticed that WLSLin configuration contains "hidden_dim" and "out_dim" parameters but because of "kernel_name" being "linear", the dimensions should not affect the calculation for WLSLin.
> 
> Hope it helps,
> Seongmin

Hi Seongmin,

Thank you for your patient explanation.
Yes, it is not dimension reduction. What I said it is because I see the conventional graph embedding as a part of graph kernels. However, in this case, it is not dimension reduction. As you said, WLS increases the number of dimensions, while other algorithms, GraphSage, GAT, GCN, WWL, keep the number of dimensions unchanged. No matter whether it increases or is unchanged, in the graph kernel experiment, all algorithms including WLS, GraphSage, GAT, GCN, WWL needs to compute kernels by graph representation.

Thank you very much.
Wei

**Comment by se-ok** [comment]
Hi Wei,

As the issue is not closed yet, I believe there are still questions remaining.
However, I cannot figure out what the questions are, so could you clarify your question again?

In case it is about confirmation:
Yes, the proposed graph kernel first computes graph representations, and then apply well-established kernels for classification.
The mentioned algorithms only differ by how to compute the representations.

Best,
Seongmin

**Comment by williamweiwu** [comment]
> Hi Wei,
> 
> As the issue is not closed yet, I believe there are still questions remaining.
> However, I cannot figure out what the questions are, so could you clarify your question again?
> 
> In case it is about confirmation:
> Yes, the proposed graph kernel first computes graph representations, and then apply well-established kernels for classification.
> The mentioned algorithms only differ by how to compute the representations.
> 
> Best,
> Seongmin

Hi Seongmin,

Thank you for your patient explanation. I will close the issue.

I appreciate your help again.
Wei
